# 基本目录配置 - 修改为您本地的路径
base_dir: /home/featurize/work/tool/OpenThinkIMG/tool_server/tool_workers
log_folder: /home/featurize/work/tool/OpenThinkIMG/tool_server/tool_workers/logs/server_log

# 本地配置中这些参数不会被使用，但保留以保持结构一致
default_calculate_gpus: 1
default_calculate_cpus: 16
default_control_cpus: 2
default_control_gpus: 0
retry_interval: 1
request_timeout: 10

# 控制器配置
controller_config:
  worker_name: controller
  job_name: controller
  calculate_type: control
  cmd:
    script-addr: ./online_workers/controller.py
    port: 20001
    host: "0.0.0.0"
  # 可选：指定conda环境
  # conda_env: "your_env_name"

# 工具工作器配置
tool_worker_config:
  - Point:
      worker_name: Point
      job_name: point
      calculate_type: control
      cuda_visible_devices: "1"
      cmd:
        script-addr: ./online_workers/molmo_point_worker.py
        port: 20027
        host: "0.0.0.0"
        model_path: "/home/featurize/work/tool/weights/Molmo-7B-D-0924"

  - SegmentRegionAroundPoint:
      worker_name: SegmentRegionAroundPoint
      job_name: sam2
      calculate_type: control
      cuda_visible_devices: "0"  # 可根据您的硬件修改
      cmd:
        script-addr: ./online_workers/SAMAroundPoint_worker.py
        port: 20036
        host: "0.0.0.0"
        sam2_checkpoint: /home/featurize/work/tool/weights/sam2-hiera-large/sam2_hiera_large.pt
        sam2_model_cfg: sam2_hiera_l.yaml
      
  - OCR:
      worker_name: OCR
      job_name: ocr
      calculate_type: control
      # 如果OCR需要GPU，可以指定设备ID
      cuda_visible_devices: "0"
      cmd:
        script-addr: ./online_workers/ocr_worker.py
        port: 20009
        host: "0.0.0.0"
  
  - GroundingDINO:
      worker_name: GroundingDINO
      job_name: groundingdino
      calculate_type: control
      cuda_visible_devices: "0"  # 可根据您的硬件修改
      cmd:
        script-addr: ./online_workers/grounding_dino_worker.py
        port: 20003
        host: "0.0.0.0"
        model-path: /home/featurize/work/tool/weights/groundingdino_swint_ogc.pth
        model-config: ../../src/GroundingDINO/groundingdino/config/GroundingDINO_SwinT_OGC.py

  - DrawHorizontalLineByY:
      worker_name: DrawHorizontalLineByY
      job_name: drawliney
      calculate_type: control
      cmd:
        script-addr: ./online_workers/DrawHorizontalLineByY_worker.py
        port: 20032
        host: "0.0.0.0"

  - DrawVerticalLineByX:
      worker_name: DrawVerticalLineByX
      job_name: drawlinex
      calculate_type: control
      cmd:
        script-addr: ./online_workers/DrawVerticalLineByX_worker.py
        port: 20089
        host: "0.0.0.0"

  - ZoomInSubfigure:
      worker_name: ZoomInSubfigure
      job_name: SelectSubplot
      calculate_type: control
      cmd:
        script-addr: ./online_workers/SelectSubplot_worker.py
        port: 20039
        host: "0.0.0.0"

  